version: "3.8"

name: demo-spring-boot-dev

services:
  todo:
    build:
      target: dev
      context: ./todo
    ports:
      - 8080:8080
    volumes:
      - ./todo:/app/

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db/keycloak
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=password
    ports:
      - 8070:8080
    command: start-dev
    depends_on:
      - keycloak_db

  keycloak_db:
    image: postgres:16.2-alpine3.19
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=keycloak
    ports:
      - 5432:5432
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 7000:8080
    environment:
      - ADMINER_DESIGN=pepa-linha

volumes:
  keycloak_db_data: